### ISSUE TITLE
Memory not freed after LCM republish

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-org/lcm-websocket-server#8]
The lcm-websocket-server seems to monotonically increase memory usage -- likely accumulating the messages in memory somewhere.

**Comment by kevinsbarnard** [comment]
Relevant:
- https://stackoverflow.com/questions/48015613/python-queue-will-not-release-the-memory-after-get
- https://docs.python.org/3/library/queue.html#queue.Queue.task_done

**Comment by carueda** [comment]
Hi @kevinsbarnard - I'm just noting this myself as well: after a rather long exercise while testing some new features for Dial, I noted some rather slow updates in the Dial UI, which, though possibly caused by my own adjustments, seemed unexpected, then I looked at `top` and saw I pretty large memory use:

```
PID    COMMAND      %CPU TIME     #TH    #WQ  #PORT MEM    PURG  CMPRS  PGRP  PPID
16431  Python       25.1 75:11.44 4      0    24    18G+   0B    4841M+ 16429 16430
...
```

**Comment by kevinsbarnard** [comment]
Hey @carueda, I may have fixed this (see commit referenced above) but haven't had a chance to test it. Just want to mention that if you want to give it a try to see if it helps your testing!

**Comment by carueda** [comment]
I've tested it with multiple log replays:

- Activity monitor showed LWS taking about 18.2MB at start of the server
- It went to ~ 19MB when about 400K messages were received by Dial
- After ~ 500K msgs (not sure exactly at what point), it went to 20.2MB and stayed like than even after 1M msgs
- so, seems like the adjustment may have actually fixed the issue, but I guess more testing is needed.

![Screenshot 2023-10-30 at 10 00 15 AM](https://github.com/mbari-org/lcm-websocket-server/assets/556505/24fdead5-5e42-40d6-94b2-065cca12af63)

**Comment by carueda** [comment]
Seems like memory demand is still increasing.

Could it be the queue itself, I wonder. Locally, I added some logging to see the behavior of the queue size.

During the exercise below I intentionally increased the speed of the player to enforce a stack trace that I've seen occasionally.  See log below.

In this back-pressure scenario, I think LWS should probably just work under a best-effort scheme: if a client cannot keep up, LWS just ignores any failed notification, continuing with the next.  (To be clear, that's in essence what actually happens with the original code: the exception makes the connection end and a new one is then established, with a brand new queue.)

But the `websocket.send` call should probably be done with a very small timeout; if it fails, then LWS can move on to the next message in the queue.

For quick experimentation, I added a `try` to just log any exception and continue assuming the task as done:

```python
            try:
                await websocket.send(event_json)
            except Exception as e:
                logger.warning(f"Failed to send event to client at {ip}:{port}: {e}")
```

When repeating the exercise with that adjustment, the queue size goes back to zero after LCM messages end, but taking a noticeable amount time due to fast player spped along with the `send` call above done with a default timeout that's presumably too large.

But again, the memory allocation seems to still be increasing.


---

```
2023-10-30 11:36:09,467 - lcm_websocket_server.lcmpubsub - INFO - GET called 81000 times  qsize=56638
2023-10-30 11:36:09,574 - lcm_websocket_server.lcmpubsub - INFO - GET called 82000 times  qsize=55638
2023-10-30 11:36:09,658 - lcm_websocket_server.lcmpubsub - INFO - GET called 83000 times  qsize=54638
2023-10-30 11:36:14,554 - lcm_websocket_server.lcmpubsub - INFO - GET called 84000 times  qsize=53638
connection handler failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1314, in close_connection
    await self.transfer_data_task
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 968, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1038, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1170, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/framing.py", line 69, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 732, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 525, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lcm_websocket_server/app.py", line 83, in republish_lcm
    await websocket.send(event_json)
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
2023-10-30 11:36:47,735 - lcm_websocket_server.app - INFO - Client connected from ::1:58649 at //STATE_KEARFOTT_COMPAS%7CLASS_ESTIMATED_STATE_RPH%7CDVL_INS_KEARFOTT_COMPAS%7CMINIROV_ESTIMATED_STATE%7CMINIROV_ESTIMATED_STATE_RPH%7CWL_DVL%7CMINIROV_ESTIMATED_STATE_C%7CMINIROV_ESTIMATED_STATE_RPH_C%7CMOLA_ESTIMATED_STATE%7CMOLA_USBL_ATT%7CMOLA_DVL
2023-10-30 11:36:47,735 - lcm_websocket_server.lcmpubsub - INFO - GET called 0 times  qsize=0
```

**Comment by kevinsbarnard** [comment]
Makes sense. Do you remember around how many messages/second hit this breaking point, or what multiplier on the log player speed you were using? This implementation certainly didn't have strict performance requirements in mind; we could port this to C or Java if you're finding Dial is running up against the throughput limit. I will look back into this memory issue when I get back next week.

**Comment by carueda** [comment]
No rush!

I played with 4x and 8x.

I think the server is OK in terms of doing (or attempting to do) fast notifications; it's the client(s) that may be become slow to ingest super rapid notifications.
